put planer_set_env in python package
so it can run in venv environment independently of nix shell

diff --git a/sh/planer_set_env b/sh/planer_set_env
--- a/sh/planer_set_env
+++ b/sh/planer_set_env
@@ -90,4 +90,9 @@ jq -n --arg arduino "$ARDUINO" \
     --arg arduino_cli "$ARDUINO_CLI" \
     '{"arduino": $arduino, "arduino_ide": $arduino_ide, "arduino_ide_data": $arduino_ide_data, "arduino_cli": $arduino_cli}'
 
+if [ "$?" -ne 0 ]; then
+    printf "error: error running jq\n"
+    exit 1
+fi
+
 exit_handler
